version: '3'
services:
  golang:
    build:
      context: .  # Build the image from the Dockerfile in the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile
      target: dev  # Specify the build stage for development
    restart: unless-stopped
    ports:
      - 8080:8080  # Application port
      - 2345:2345  # Delve debugger port
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - .:/app:rw,delegated  # Mount the current directory to /app in the container
    working_dir: /app
    command: ["air"]  # Override CMD to ensure Air runs
    environment:
      - ENV=development  # Add any additional environment variables needed for development
      - GO_ENV=development

  rabbitmq:
    build:
      context: .
      dockerfile: ./Dockerfile.rmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
